name: clockwork

inputs:
  - compute.h
  - compute_mapped.json

outputs: 
  - design.v
  - design_verilog_collateral.sv

commands:
  - sh run_clockwork.sh

preconditions:
  - assert File( 'inputs/compute.h' )              # must exist
  - assert File( 'inputs/compute_mapped.json' )              # must exist

postconditions:
  - assert File( 'outputs/design.v' )        # must exist
  - assert File( 'outputs/design_verilog_collateral.sv' )        # must exist